# Generated by Django 2.2.6 on 2019-11-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localName', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('phoneNumber', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaName', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=5)),
                ('ingredient', models.ManyToManyField(to='pizzaonline.Ingredients')),
            ],
        ),
    ]
