# Generated by Django 2.2.6 on 2019-11-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaonline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.AlterField(
            model_name='store',
            name='phoneNumber',
            field=models.IntegerField(),
        ),
    ]
