# Generated by Django 2.2.6 on 2019-11-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaonline', '0002_auto_20191106_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
