# Generated by Django 2.2.6 on 2019-11-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaonline', '0003_auto_20191106_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ManyToManyField(to='pizzaonline.Size'),
        ),
    ]
