# Generated by Django 2.2.6 on 2019-11-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaonline', '0004_pizza_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=11)),
                ('bday', models.DateField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pssword', models.CharField(max_length=200)),
            ],
        ),
    ]
